streaak/keyhacks

- README.md
> Added Microsoft Azure Shared Access Sigantures

- README.md
> Fix Bit.ly Url

- README.md
"Remember to keep your tokens secret; treat them just like passwords! They act on your behalf when interacting with the API. Don’t hardcode them into your programs; instead, opt to use them as environment variables." _Source: https://asana.com/developers/documentation/getting-started/auth#personal-access-token_
> Adding Asana access token

- README.md
Zendesk access token should remain secret.
> Add Zendesk access token

- README.md
> Added Microsoft Azure

- README.md
> Added Google Cloud Messaging

- README.md
> Added Firebase

- README.md
Another way of checking AWS credentials permissions
> More info on AWS creds (IAM and privilege management)

- README.md
> Add stripe-payments token

- README.md
Even though S3 is famous among AWS resource not every account will have S3 buckets. So I have updated the command and removed S3 bucket listing command.
> Updated AWS credential checker

- README.md
As suggested in #42, adding this onto pre-existing Paypal checks.
Closes #42
> Further checks added for Paypal Access tokens

- README.md
Hi team,
With my original pull request, I've noticed I missed a whole set of endpoints as Google Maps branches out in different services such as Elevation, Directions, Static Map, etc.
This request will update those missing endpoints along with adding the price per 1000 requests which should provide additional helpful information when demonstrating the impact.
Thank you,
\- m-qt
> Add additional Google Maps endpoints along with pricing

- README.md
Added details related to https://www.loqate.com/ api key usage.
> Added details related to https://www.loqate.com/

- README.md
Adding ipstack API used for geolocation. 
Documentation: https://ipstack.com/documentation
Pricing: https://ipstack.com/product
> Add ipstack api

- README.md
Hi @streaak,
Recently I've stumbled upon NPM token disclosure and spent some time figuring out a way to verify it. In order to save others time I've decided to update this amazing repo adding NPM token verification steps.
Thanks for the project :)
> Add NPM token

- README.md
Hey!
I've decided to add some information about verifying Google Cloud Service Account credentials. I think it's not complete but it's more than nothing 😃 
Again thanks for the project!
> Add Google Cloud Service Account credentials

- README.md
Personal API key should not be shared according to https://docs.newrelic.com/docs/apis/get-started/intro-apis/types-new-relic-api-keys
> New Relic keys

- README.md
Hey :)
I have recently encountered with Azure Application Insights, It allows various methods/ways for authentication on of which is API key based.
Their API reference:
https://dev.applicationinsights.io/documentation/Authorization/API-key-authentication
--
Regards,
@bugbaba
> Azure Application Insights APP ID and API key

- README.md
I recently found a Google/YouTube API key and used this as an example in a bug report.
> Added in YouTube API Key

- README.md
Please see commit descriptions for fixes and updates
> PR for a few new API keys and Issues

- README.md
Adding [weglot api key verification](https://weglot.com/)
> Add weglot

- README.md
This makes the readme look like it was intended
> Remove unnecessary back quotes

- README.md
- https://app.delighted.com/docs/api
- https://app.delighted.com/docs/api/getting-metrics
> Added "Delighted" Api key testing instructions

- README.md
Example output (good):
```
$ curl https://api.opsgenie.com/v2/alerts -H 'Authorization: GenieKey redacted-reda-cted-reda-ctedredacted'
{"data":[{"seen":true,"id":"b009e3b0-9f2d-4f75-9f7f-f9d04cead481-1659735552430","tinyId":"25812","alias":"fe584c5a33da2d4d2142e02d24282368ab26f3075ea6eb7d850f4aedadd39b8b","message":"[Prometheus]... more JSON
```
Example output (bad):
```
$ curl https://api.opsgenie.com/v2/alerts -H 'Authorization: GenieKey redacted-reda-cted-reda-ctedredacted'
{"message":"Could not authenticate","took":0.002,"requestId":"8a88410f-3129-483d-87b7-b09ffdb1ac2c"}
```
> Adding OpsGenie API Key

- README.md
Adding Microsoft Teams Webhook test
> Add Microsoft Teams Webhook
